defaults:
  - fold_mobile_dp

agent:
  agent_name: equibot

model:
  hidden_dim: 4 # was 32
  encoder:
    backbone_type: vn_pointnet
    
training:
  batch_size: 1024  # 1024 for equibot on rtx a4500 20gb vram 480p dataset 